#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib-test.sh"

require_file ".github/workflows/validate.yml"
require_file ".github/workflows/terraform-plan.yml"
require_file ".github/workflows/terraform-apply.yml"
require_file ".github/workflows/aks-app-deploy.yml"
require_file ".github/dependabot.yml"
require_file ".github/CODEOWNERS"
require_file "docs/ci-cd.md"
require_file "docs/app-deployment.md"
require_file "docs/cost-estimation.md"
require_file "docs/diagram-architecture.md"
require_file "docs/remote-state.md"
require_file "docs/scaling-strategy.md"
require_file "docs/security-considerations.md"
require_file "docs/secret-management.md"
require_file "docs/terraform-operations.md"
require_file ".tflint.hcl"
require_file ".checkov.yml"
require_file "trivy.yaml"
require_file ".gitleaks.toml"
require_file "policies/conftest/terraform.rego"
require_file "scripts/security-scan.sh"
require_file "scripts/policy-check.sh"
require_file "scripts/terraform-plan-ci.sh"
require_file "scripts/terraform-apply-ci.sh"

require_pattern ".github/workflows/validate.yml" "security-events:[[:space:]]*write" "CI workflow can upload security scan results"
require_pattern ".github/workflows/validate.yml" "scripts/security-scan\\.sh" "CI workflow runs strict security scans"
require_pattern ".github/workflows/validate.yml" "terraform-linters/setup-tflint" "CI workflow installs TFLint"
require_pattern ".github/workflows/validate.yml" "github/codeql-action/upload-sarif" "CI workflow uploads SARIF to code scanning"

require_pattern ".github/workflows/terraform-plan.yml" "id-token:[[:space:]]*write" "Terraform plan workflow uses OIDC permissions"
require_pattern ".github/workflows/terraform-plan.yml" "azure/login@v2" "Terraform plan workflow uses Azure OIDC login"
require_pattern ".github/workflows/terraform-plan.yml" "scripts/terraform-plan-ci\\.sh" "Terraform plan workflow uses CI plan script"
require_pattern ".github/workflows/terraform-plan.yml" "scripts/policy-check\\.sh" "Terraform plan workflow runs policy-as-code"
require_pattern ".github/workflows/terraform-plan.yml" "actions/upload-artifact@v4" "Terraform plan workflow uploads reviewed plan artifacts"
require_pattern ".github/workflows/terraform-plan.yml" "infracost breakdown" "Terraform plan workflow includes Infracost cost estimates"

require_pattern ".github/workflows/terraform-apply.yml" "environment:[[:space:]]*\\$\\{\\{ inputs\\.environment \\}\\}" "Terraform apply workflow uses GitHub Environment gates"
require_pattern ".github/workflows/terraform-apply.yml" "confirm.*apply|Type apply to confirm" "Terraform apply workflow requires explicit confirmation"
require_pattern ".github/workflows/terraform-apply.yml" "scripts/terraform-apply-ci\\.sh" "Terraform apply workflow applies the reviewed plan artifact"
require_pattern ".github/workflows/terraform-apply.yml" "concurrency:" "Terraform apply workflow serializes applies"

require_pattern ".github/workflows/aks-app-deploy.yml" "self-hosted" "AKS app deployment requires a self-hosted runner"
require_pattern ".github/workflows/aks-app-deploy.yml" "aks-private" "AKS app deployment requires private AKS network access"
require_pattern ".github/workflows/aks-app-deploy.yml" "az aks get-credentials" "AKS app deployment fetches cluster credentials"
require_pattern ".github/workflows/aks-app-deploy.yml" "Setup Helm" "AKS app deployment installs Helm"
require_pattern ".github/workflows/aks-app-deploy.yml" "scripts/validate-webapp\\.sh" "AKS app deployment can validate HTTP 200"
require_pattern "docs/app-deployment.md" "helm rollback" "App deployment runbook documents rollback"
require_pattern "docs/app-deployment.md" "Application Gateway" "App deployment runbook documents public validation path"
require_pattern "docs/remote-state.md" "restore-terraform-state-blob\\.sh" "Remote state runbook documents restore script"
require_pattern "docs/secret-management.md" "Key Vault Secrets User" "Secret management runbook documents least privilege secret access"
require_pattern "docs/terraform-operations.md" "Drift Detection" "Terraform operations runbook documents drift detection"
require_pattern "docs/diagram-architecture.md" '[`][`][`]mermaid' "Architecture diagram document contains Mermaid diagrams"
require_pattern "docs/diagram-architecture.md" "Application Gateway WAF" "Architecture diagram documents Application Gateway"
require_pattern "docs/cost-estimation.md" "Estimated monthly total" "Cost estimation document includes monthly totals"
require_pattern "docs/cost-estimation.md" "Azure Retail Prices API" "Cost estimation document references Azure retail pricing"
require_pattern "docs/scaling-strategy.md" "Scaling Layers" "Scaling strategy document explains platform scaling layers"
require_pattern "docs/scaling-strategy.md" "validate-network-controls\\.py" "Scaling strategy document includes post-scale validation"
require_pattern "docs/security-considerations.md" "Application Gateway WAF" "Security considerations document explains WAF protection"
require_pattern "docs/security-considerations.md" "validate-network-controls\\.py" "Security considerations document references network validation"

finish_tests
